version: '3'
services:
  flutter-web:
    image: antoniopicone/flutter_web
    
    ports:
      - 8080:8080
    
    # To avoid running root user, specify user with UID 1000 (wich is devuser or linux default)
    user: "1000"

    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so we will mount '..'. We'll then reference this as the
      # workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace:cached

      # [Optional] If you are using SSH keys w/Git, mount your .ssh folder to
      # /root/.ssh-localhost so we can copy its contents
      # - ~/.ssh:/root/.ssh-localhost:ro

    # # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity